language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=django20
      script: make validate
    - python: 3.5
      env: TOXENV=django21
      script: make validate
    - python: 3.5
      env: TESTNAME=quality
      script:
        - make quality
        - make pii_check
    - python: 3.5
      env: TESTNAME=translations
      script: make validate_translations
sudo: false

cache: pip
install:
    - pip install -U pip wheel codecov
    - make requirements
after_success:
    - codecov
